// vim: set expandtab tabstop=3

// to check syntax quickly
// idlpp  -I${OSPL_HOME}/etc/idl -l c  tsn.idl

/*
 *      OpenSplice DDS IDL definition for TSN -  ONLY USING FOR TEST PROGRAM
 */

module TSN 
{
   struct Msg
   {
      string name;
      string message;
    };
   #pragma keylist Msg name
};


